train:
  batch_size: 16
  num_epochs: 20
  lr: 0.0001
  weight_decay: 0.00001
  warmup_steps: 10 # 0 if activating reduceonplateau
  optimizer_type: adamw # (sgd, adam, adamw)
  resampling: True # True if sample number is considerably imbalanced among categories 
  device: cuda # (cuda, cpu)
  accum_step: 1 # >1 means gradient accumulation over iterations
  mode: accum # (accum, avg), if the dataset is too large, set to avg to run AverageMeter over batches
  metric_names: ['acc', 'avg_acc'] # ('acc', 'avg_acc', 'auc', 'acc@3', 'acc@5')
  criterion: # specify cost function
    cse: 
      weight: 1
      config: {}
  monitor_metric: acc
  seed: 2013 # -1 for not fixing random seed
   
data:
  dataset: preloadres_isup
  config:
    transforms:
      tabular:
        name: identity
        config: {}
      image:
        train_shape: [224, 224]
        test_shape: [224, 224]
        norm: True
        aug_rate: 0.95
        train_augs: "T.Compose([ \
        T.RandomResizedCrop(size=(224, 224), scale=(0.2, 1.0), ratio=(0.75, 1.3333)), \
        T.RandomHorizontalFlip(p=0.5), \
        T.RandomGrayscale(p=0.2), \ 
        T.RandomApply([T.GaussianBlur(kernel_size=(29, 29), sigma=(0.1, 2.0))], p=0.5)
        ])"
        test_augs: ""
    modal: ['img', 'tab']
    kwd: clip_gpt

model:
  name: res_mm
  wrapper:
    wrapper_input: dict # (tuple) | (dict)
    model_input: dict # (tensor) | (dict)
    model_output: tensor # (tensor) | (dict)
    kwd:  # only applicable when dataloader item is of type (dict), but model input is of type (tensor)
  config:
    tab_emb_dim: 1024
    num_classes: 3
    feat_dim: 1024
    fusion: attn
    image_encoder: rn50_clip_res
    tab_encoder: identical
    complex_classifier: False
    nhead: 4
    source_idx: [3,4,5,6,7,8,9,10,11,12,13]
    target_idx: [3,3,4,4,4,5,5,6,6,7,7]
    zero_conv: True


    
