train:
  batch_size: 64
  num_epochs: 100
  lr: 0.0001
  weight_decay: 0.01
  warmup_steps: 100 # 0 if activating reduceonplateau
  optimizer_type: adamw # (sgd, adam, adamw)
  resampling: False # True if sample number is considerably imbalanced among categories 
  device: cuda # (cuda, cpu)
  accum_step: 1 # >1 means gradient accumulation over iterations
  mode: accum # (accum, avg), if the dataset is too large, set to avg to run AverageMeter over batches
  metric_names: ['acc', 'avg_acc'] # ('acc', 'avg_acc', 'auc', 'acc@3', 'acc@5')
  criterion: # specify cost function
    cse: 
      weight: 1
      config: {}
  monitor_metric: acc
  seed: 2025 # -1 for not fixing random seed
   
data:
  dataset: preload_oasis
  config:
    transforms:
      tabular:
        name: identity
        config: {}
      image:
        train_shape: [224, 224]
        test_shape: [224, 224]
        norm: True
        aug_rate: 1
        train_augs: "T.Compose([ \
        T.Resize(size=(224, 224)), \
        T.RandomHorizontalFlip(p=0.5), \
        T.RandomApply([T.ColorJitter(brightness=[0.2, 1.8], contrast=[0.2, 1.8], saturation=[0.2, 1.8], hue=0)], p=0.8), \ 
        T.RandomGrayscale(p=0.2), \ 
        T.RandomApply([T.GaussianBlur(kernel_size=(29, 29), sigma=(0.1, 2.0))], p=0.5), \
        ])"
        test_augs: ""
    modal: ['tab', 'img']
    kwd: onehot_noaug

model:
  name: ppnet
  wrapper:
    wrapper_input: dict # (tuple) | (dict)
    model_input: dict # (tensor) | (dict)
    model_output: tensor # (tensor) | (dict)
    kwd:  # only applicable when dataloader item is of type (dict), but model input is of type (tensor)
  config:
    tab_emb_dim: 20
    num_classes: 4

    
