train:
  batch_size: 32
  num_epochs: 25
  lr: 0.0000005
  weight_decay: 0.001
  warmup_steps: 100 # 0 if activating reduceonplateau
  optimizer_type: adamw # (sgd, adam, adamw)
  resampling: True # True if sample number is considerably imbalanced among categories 
  device: cuda # (cuda, cpu)
  accum_step: 1 # >1 means gradient accumulation over iterations
  mode: accum # (accum, avg), if the dataset is too large, set to avg to run AverageMeter over batches
  metric_names: ['acc', 'auc', 'avg_acc', 'f1'] # ('acc', 'avg_acc', 'auc', 'acc@3', 'acc@5')
  criterion: # specify cost function
    cse: 
      weight: 1
      config: {}
  monitor_metric: auc
  seed: 2023 # -1 for not fixing random seed
   
data:
  dataset: preloadres_covidar
  config:
    transforms:
      tabular:
        name: identity
        config: {}
      image:
        train_shape: [224, 224]
        test_shape: [224, 224]
        norm: True
        aug_rate: 0.95
        train_augs: "T.Compose([ \
        T.Resize((224, 224)),
        T.RandomResizedCrop(size=(224, 224), scale=(0.2, 1.0)), \
        T.RandomHorizontalFlip(p=0.5), \
        T.RandomRotation(degrees=45), \
        T.ColorJitter(brightness=0.5, contrast=0.5, saturation=0.5), \
        ])"
        test_augs: ""
    modal: ['img', 'tab']
    kwd: pubmedclip_gpt
    sample: True

model:
  name: res_mm
  wrapper:
    wrapper_input: dict # (tuple) | (dict)
    model_input: dict # (tensor) | (dict)
    model_output: tensor # (tensor) | (dict)
    kwd:  # only applicable when dataloader item is of type (dict), but model input is of type (tensor)
  config:
    tab_emb_dim: 1024
    num_classes: 2
    feat_dim: 1024
    fusion: attn
    image_encoder: rn50_clip_res
    tab_encoder: identical
    source_idx: [0,3,4,5,6,7,8,9,10,11,12,13,14,15]
    target_idx: [0,1,1,1,2,3,3,4,4,5,6,6,6,0]
    nhead: 1
    zero_conv: True


    
